### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by phoebe0920** [AHupuJR/RFNet#1]
thank you for your opening code!
How can I get to the  depth of cityscape？from the cityscape website，I download it but  without disparity ,can you share with me ? Thank you very much

**Comment by AHupuJR** [comment]
To obtain Cityscapes disparity images, you have to send an requisting email. You can find that at https://www.cityscapes-dataset.com/downloads/    : )

**Comment by phoebe0920** [comment]
excuse me. l log in the cityscape website, and log in my icloud. but nothing appears, where should the email be sent.can you give me some advices ？thanks




| |
彭映青
|
|
邮箱：phoebe_pyq@163.com
|

签名由 网易邮箱大师 定制

On 03/22/2020 00:31, LeoSun wrote:

To obtain Cityscapes disparity images, you have to send an requisting email. You can find that at https://www.cityscapes-dataset.com/downloads/ : )

**Comment by phoebe0920** [comment]
> To obtain Cityscapes disparity images, you have to send an requisting email. You can find that at https://www.cityscapes-dataset.com/downloads/ : )

excuse me. l log in the cityscape website, and log in my icloud. but nothing appears, where should the email be sent.can you give me some advices ？thanks

**Comment by phoebe0920** [comment]
> To obtain Cityscapes disparity images, you have to send an requisting email. You can find that at https://www.cityscapes-dataset.com/downloads/ : )
excuse me.
How long after you send the e-mail?

**Comment by phoebe0920** [comment]
> To obtain Cityscapes disparity images, you have to send an requisting email. You can find that at https://www.cityscapes-dataset.com/downloads/ : )
excuse me,
How long do you receive a reply after sending the email?

**Comment by AHupuJR** [comment]
About a week :)

**Comment by phoebe0920** [comment]
> About a week :)

Ok, thank you very much!

**Comment by phoebe0920** [comment]
It's been a week and I still haven’t received the email. Can you share it to this email(phoebe_pyq@163.com)?   Thanks!!!

**Comment by AHupuJR** [comment]
Sorry, I really wanto to help you but as far as I know it's not allowed to share that privately. I believe Cityscapes will send you an email soon!

**Comment by phoebe0920** [comment]
So sad. It has been more than ten days since the mail was sent.  I wrote directly my Cityscapes username and a list of required packages in the body of the mail. I want to confirm whether my operation is wrong. Thank you again!!

**Comment by AHupuJR** [comment]
That's right, maybe they can't work now :(

**Comment by phoebe0920** [comment]
Due to the impact of the COVID-19, they may not have been to work yet. I am also a student. I can’t do experiments without a dataset. Could you please share the data set with me? Thank you very much.
