### ISSUE TITLE
Problem with loading weights

### ISSUE THREAD

**Issue by Klaiddom** [AHupuJR/RFNet#2]
Hi, first of all thank you for sharing the code!

I have a problem with loading weight's, when i start the eval.py i get error that model SemsegModel dosen't exist in file models.rfnet.py, so i changed SemsegModel to RFnet model, and when I try load weight i get an error that some layers do not appear in model.

**Comment by AHupuJR** [comment]
Thank you for your interest!
That's because we test a lot of different network layers in the origin version. Now I modified the code so that weights can be loaded now(still some weights are not needed but it doesn't matter). Couple of days later we will update the weights :)
